### ISSUE TITLE
Navbar icon error when called navigationPage.PopToRootAsync()

### ISSUE THREAD

**Issue by felagund18** [nativecode-dev/oss-xamarin#27]
Hi,
In my app, there are two toolbar items in main navigationPage;

<pre><code>//App.cs
Nav = new NavigationPage (new PageHome ());
Nav.BarTextColor = Color.White;
Nav.ToolbarItems.Add (new ToolbarItem {
    Icon = "ic_action_toolbar_icon2.png",
    Command = new Command(new Action(() => {
        App.Nav.PopToRootAsync();
    })),
});
Nav.ToolbarItems.Add (new ToolbarItem {
    Icon = "ic_action_toolbar_icon3.png",
    Command = new Command(new Action(() => {
        var page = new PageDays();
        App.Nav.PopToRootAsync();
        App.Nav.PushAsync(page);
    })),
});
MainPage = new PageMaster ();
</code>
</pre>

<pre>
<code>//PageMasterDetail.cs
Detail = App.Nav;
Master = new PageMenu ();
</code>
</pre>

1. App starts normally
   ![device-2015-06-27-003900](https://cloud.githubusercontent.com/assets/1384327/8381221/22cc81ee-1bdf-11e5-9ac7-79f77e3fc1ac.png)
2. Goes to Page1 by tapping second toolbarItem
   ![device-2015-06-27-003922](https://cloud.githubusercontent.com/assets/1384327/8381228/39bd67f6-1bdf-11e5-845f-1b06a5cba721.png)
3. When clicked first toolbarItem, it calls NavigationPage.PopToRootAsync() method and then icon should be "Sandwich" not an arrow, right?
   ![device-2015-06-27-003931](https://cloud.githubusercontent.com/assets/1384327/8381257/6ea0c918-1bdf-11e5-891b-205bfcacb51a.png)

**Comment by mikepham** [comment]
Yeah, that definitely looks like a bug. There's special code to handle the case of NavigationPages and the back arrow. I'll look into it this weekend.

**Comment by mikepham** [comment]
Thanks for reporting the issue. This has been fixed in 1.0.0.74.
It also happened to expose another bug when pushing multiple pages onto the navigation. See the release notes.

There's also now a demo for nested navigation inside a MasterDetailPage.

**Comment by felagund18** [comment]
Many thanks :)))
