### ISSUE TITLE
Small PageTitle in Landscape Mode

### ISSUE THREAD

**Issue by felagund18** [nativecode-dev/oss-xamarin#35]
Hi, :)
When app starts in portrait mode(orientation), navBar title is fine...
![1](https://cloud.githubusercontent.com/assets/1384327/8397652/de4aa8e8-1d87-11e5-91ca-89ef070624a6.PNG)
![2](https://cloud.githubusercontent.com/assets/1384327/8397654/e0be593a-1d87-11e5-9c92-1358454b2224.PNG)

But when app start in landscape mode, then navBar title is became very small
![3](https://cloud.githubusercontent.com/assets/1384327/8397658/f44114ac-1d87-11e5-9099-6299ed2cb609.PNG)
even after changing the orientation, it still has a small title
![4](https://cloud.githubusercontent.com/assets/1384327/8397663/073ae95c-1d88-11e5-80ce-e0bfec83b070.PNG)

Is it a bug?

**Comment by mikepham** [comment]
We don't do anything with the title sizes, so it might be a bug in AppCompatDelegate. I'll have to create a normal Android project and see if that's the case. Requires more research, so I don't want to label as a bug just yet. Thanks!

**Comment by mikepham** [comment]
Sorry for the delay, finally had a chance to look into this. Looks like it's a Forms issue. I created a standard Forms app and it displays the same behavior. I would suggest maybe adding a custom style and change the ActionBar's text style there.

On Lollipop:
![portrait](https://lh6.googleusercontent.com/HlV5890nNRjoC3J4OaTUPmjOFPAiE0LqJs7MkQn4w_6Lx3K4mGwPZHIobCYyX5ZdrkcGwRHGBhIyTdY=w1914-h1067)
![landscape](https://lh4.googleusercontent.com/d1mbZ8W1IpYcKYsvKVJCJDctjzfdJxS8sUTiTHQq-gXShXKP5EAGI_Yu8S2d2wCmt5cRf9QrxbQmaDw=w1914-h1067)
